import { RelationType } from "../utils/types";
// import { DefaultTheme } from "styled-components";

const theme = {
  mainFont:
    '"Proxima Nova", "IBM Plex Sans", "Barlow", "Helvetica Neue", Helvetica, "Droid Sans", sans-serif',
  secondaryFont: '"SangBleu Republic", "Calluna", "Lapture", serif',
  fontSizeS: "15px",
  fontSizeM: "20px",
  fontSizeL: "28px",
  mainTextColor: "rgba(0, 0, 0, 0.84)" /* Stolen from Medium */,
  lightTextColor: "#ffffff",
  linkTextColor: "#0077CC", // Stackoverflow
  visitedLinkTextColor: "#0077CC",
  hoverLinkTextColor: "#33AAFF",
  secondaryTextColor: "#72727c",
  focusColor: "#5B44E8",
  appBG: "#FFFFFF",
  sidebarBG: "rgba(255, 255, 255, 0.78)",
  darkBG: "rgba(0, 0, 0, 0.84)" /* Stolen from Medium */,
  lightBG: "#EFEFF2",
  inputBG: "#EFEFF2",
  errorBG: "#E37777",
  successBG: "#B4DE7E",
  border: "#ededed",
  borderHover: "#8A879B",
  surfaceHover: "#B8B7BC",
  confirmingTextColor: "#366936",
  refutingTextColor: "#752F40",
  refutingBackgroundColor: "#F3DFD7",
  borderWidth: "2px",
  inputPaddingLR: "8px",
  inputPaddingTB: "4px",
  inputLRSpacing: "4px",
  inputTBSpacing: "4px",
  marginLR: "12px",
  marginTB: "12px",
  inputMarginTB: "12px",
  blockPadding: "12px",
  blockSpacingTB: "20px",
  navBarHeight: "54px",
  appMaxWidth: "1024px",
  appSidebarWidth: "240px",
  appMiniSidebarWidth: "130px",
  appPaddingLR: "24px",
  appPaddingTB: "12px",
  longFieldHeight: "3em",
  radius: "2px",
};

export const RELATION_COLORS = {
  [RelationType.IsOwned]: "#7E57C2",
  [RelationType.IsControlled]: "#2196F3",
  [RelationType.JobDependsOn]: "#009688",
  [RelationType.ValueExchange]: "#8BC34A",
  [RelationType.Family]: "#ffd32a",
  [RelationType.Love]: "#ef5777",
  [RelationType.Opposition]: "#ff3f34",
  [RelationType.IsInfluenced]: "#ffa801",
  [RelationType.Attendance]: "#4DD0E1",
  [RelationType.GroupMember]: "#4DD0E1",
  [RelationType.Other]: "#1e272e",
};

export default theme;
